name: sleep_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  - seaborn
  - requests
  - ipykernel
  - scikit-learn
  - pip
  - pip:
      - boto3
      - mne